version: "3"
services:
  play_song_ms:
    build: .
    environment:
      PORT: '3004'
    ports:
      - "3004:3004"
  songs_db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
